skip_local_validator = true

[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_lob = "Honq7kkNfptR6XF5H4zn2jWqSmNRsteCpGwB8iG393cR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
